"""remove the revoked from refresh table

Revision ID: 91e1820d5b07
Revises: a01d7a2e1654
Create Date: 2026-07-26 01:13:31.783457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e1820d5b07'
down_revision: Union[str, Sequence[str], None] = 'a01d7a2e1654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
