"""add refresh tokens

Revision ID: a01d7a2e1654
Revises: b4c712023aeb
Create Date: 2026-07-25 00:26:41.385533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01d7a2e1654'
down_revision: Union[str, Sequence[str], None] = 'b4c712023aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('data_usages', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_data_usages_date'), table_name='data_usages')
    op.drop_constraint(op.f('uq_data_usage_user_date'), 'data_usages', type_='unique')
    op.create_index(op.f('ix_data_usages_id'), 'data_usages', ['id'], unique=False)
    op.drop_constraint(op.f('data_usages_user_id_fkey'), 'data_usages', type_='foreignkey')
    op.create_foreign_key(None, 'data_usages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_usages', type_='foreignkey')
    op.create_foreign_key(op.f('data_usages_user_id_fkey'), 'data_usages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_data_usages_id'), table_name='data_usages')
    op.create_unique_constraint(op.f('uq_data_usage_user_date'), 'data_usages', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_data_usages_date'), 'data_usages', ['date'], unique=False)
    op.alter_column('data_usages', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
