"""add public_id to documents

Revision ID: d5640eb9976a
Revises: 892233d4af11
Create Date: 2026-06-09 22:57:41.117026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5640eb9976a'
down_revision: Union[str, Sequence[str], None] = '892233d4af11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('public_id', sa.String(32), nullable=False))
    op.create_unique_constraint(None, 'documents', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'public_id')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
